# Generated by Django 4.2.4 on 2023-08-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_scope_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AddField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='articles.tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='000', max_length=50),
            preserve_default=False,
        ),
    ]
